### ISSUE TITLE
For me to use this I need to know 1 thing

### ISSUE THREAD

**Issue by DrZed** [webmasterdro/pw-web#1]
Does this function with PWI 1.5.5 v156 based server can it show "Online" and list the # online players and be able to send gifts to said players?
As the current pw-web doesn't function for that it eternally shows offline even with online server, ports properly set, and the version set to 101.
Granted the PW-API by huludini is what's broken not the site itself.

**Comment by DrZed** [comment]
Holy crap dude thanks, such a simple thing always seems to break code.

Thank you a ton man. (the glinkd GLS1 to 0.0.0.0 was the fix I needed.)

(Minor background I am a programmer although I only do scripting and Object Oriented code (Java/C#))
(I'm amateur at networking and website code)
The smallest of things always are the causes for biggest frustrations

Would you care to see a list of additions/changes to the site (in another thread ofcourse) or no?

Also just because you haven't released a version doesn't mean it's unusable or anything since the code is functional and is open source.

**Comment by webmasterdro** [comment]
Hi,

Glad to know that you got working! I agree with you smallest things always cause headaches. If you wanna contact me I'm using Discord: Pedro 💻#8056 (the emoji makes part of the username).

**Comment by DrZed** [comment]
Will do when I get back on my PC.
