### ISSUE TITLE
mysql issue

### ISSUE THREAD

**Issue by Ramonymous** [webmasterdro/pw-web#3]
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null, `transaction_status` varchar(191) not null default 'initiated', `' at line 1

create table `donates` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned not null, `package_id` char(36) not null, `data` json not null, `transaction_status` varchar(191) not null default 'initiated', `transaction_reference` char(36) not null, `transaction_code` text null, `paid_at` timestamp null, `delivered_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null)

always failed~

**Comment by webmasterdro** [comment]
Hello,

Sorry for the delay to answer. This project contains few bugs and unfinished features, that's why you're getting this error. I'll probably get back to this project when I have some free time, and release a basic version.
